name: CI / CD Pipeline

on:
    push:
        branches: [main, developer]

jobs:
    job_test:
        name: Executando o job
        runs-on: ubuntu-latest
    steps:
    - name: Checkout code
        uses: actions/checkout@v2

    - name: Executando um comando simples
        run: echo "Olá, esse é o nosso primeiro job no Github action"
with:
node - version: '14'

  - name: Install dependencies
run: npm install

  - name: Run tests
run: npm test
